export const achievementsData = [
    {
        id: 1,
        title: 'Horror Footage Finder',
        desc: `Côté Front - Site internet permettant de mettre en lien les goûts cinématographique d'un utilisateur en matière de film d'horreur et des listes de films proposées. `,
        image: require('../../assets/images/HFF.jpg').default,
        link: "https://github.com/CorentinCouzigou/Horror-Footage-Finder-Front",
        nature: "Front",
    },
    {
        id: 2,
        title: 'Horror Footage Finder',
        desc: `Côté Back - Site internet permettant de mettre en lien les goûts cinématographique d'un utilisateur en matière de film d'horreur et des listes de films proposées.`,
        image: require('../../assets/images/HFF.jpg').default,
        link: "https://github.com/CorentinCouzigou/Horror-Footage-Finder-Back",
        nature: "Back",
    },
    {
        id: 3,
        title: 'Wearther application',
        desc: "Application pour météo selon la ville séléctionnée par l'utilisateur.",
        image: require('../../assets/images/HomeClearSky.png').default,
        link: "https://github.com/CorentinCouzigou/Weather-application",
        nature: "Front",
    },
    {
        id: 4,
        title: 'Pokédex',
        desc: "Pokédex réalisé entièrement côté back, rendu avec le moteur de template EJS ",
        image: require('../../assets/images/pokedexHome.png').default,
        link: "https://github.com/CorentinCouzigou/Pokedex",
        nature: "Back",
    },
    {
        id: 5,
        title: 'Netflux',
        desc: `Clone de netflix`,
        image: require("../../assets/images/netfluxhome.png").default,
        link: "https://github.com/CorentinCouzigou/Netflux-CloneOfNetflix",
        nature: "Front",
    },
    {
        id: 6,
        title: 'O\'quiz',
        desc: "Quiz interractif",
        image: require('../../assets/images/oquiz.png').default,
        link: "https://github.com/CorentinCouzigou/S5--O-quizz--Architecture-Sequelize-securit-",
        nature: "Back",
    },
    {
        id: 7,
        title: 'My To-do-list',
        desc: "To-do-list en javascript avec Drag and Drop sans l'utilisation de bibliothèque",
        image: require('../../assets/images/todolist.png').default,
        link: "https://github.com/CorentinCouzigou/to-do-list-front-V2",
        nature: "Front",
    },
    {
        id: 8,
        title: 'My To-do-list',
        desc: "To-do-list Côté back avec stockage des stages dans un fichier Json",
        image: require('../../assets/images/todolist.png').default,
        link: "https://github.com/CorentinCouzigou/to-do-list-back",
        nature: "Back",
    },

    {
        id: 9,
        title: 'Converter',
        desc: "Converter en euros avec la device de votre choix.",
        image: require('../../assets/images/converter2.png').default,
        link: "https://github.com/CorentinCouzigou/Converteur-React",
        nature: "Front",
    },

];